Update extrainst_ and prerm to not destroy the iPhone 4S with Siri already installed.

diff --git a/layout/DEBIAN/extrainst_ b/layout/DEBIAN/extrainst_
--- a/layout/DEBIAN/extrainst_
+++ b/layout/DEBIAN/extrainst_
@@ -4,24 +4,28 @@ declare -a cydia
 cydia=($CYDIA)
 
 if [[ $1 == install ]]; then
-    # install only on install, not if upgrading, etc.
-    # FIXME: for future ugprades, this logic may need to change
-    SpireInstaller
-
-    if [ $? = 0 ]; then
-        # force a reboot on a successful install
-        if [[ ${CYDIA+@} ]]; then
-            eval "echo 'finish:reboot' >&${cydia[0]}"
-        fi
-
-        exit 0
+    # XXX: this is not a good test as future devices might include siri
+    if [[ "$(uname -m)" == "iPhone4,1" ]]; then
+        echo "Not re-installing Siri on an iPhone 4S."
     else
-        # cleanup to remove partial installs
-        SpireRemover
+        # install only on install, not if upgrading, etc.
+        # FIXME: for future ugprades, this logic may need to change
+        SpireInstaller
 
-        exit 1
+        if [ $? = 0 ]; then
+            # force a reboot on a successful install
+            if [[ ${CYDIA+@} ]]; then
+                eval "echo 'finish:reboot' >&${cydia[0]}"
+            fi
+
+            exit 0
+        else
+            # cleanup to remove partial installs
+            SpireRemover
+    
+            exit 1
+        fi
     fi
-
 fi
 
 
